WIP: reseting to original build

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -1,14 +1,10 @@
 name: WIP Build & Test
 
+
 on:
   pull_request:
   push:
-    branches: ["main-ramon", "production-ramon"]
-
-permissions:
-  id-token: write
-  contents: read
-  actions: read
+    branches: ["main-ramon", RITM0194581-image-prefix, "production-ramon"]
 
 env:
   APP_NAME: ${{ vars.APP_NAME }}
@@ -17,55 +13,280 @@ env:
   RUN_UNIT_TESTS: ${{ vars.RUN_UNIT_TESTS }}
 
 jobs:
-  test:
-    name: Unit tests
+  build:
+    name: Build and test container image
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      id-token: write
+      actions: read
+    # Currently pushes to dev but should change to push to prod when account is set up.
+    # Even further on, this should push to a centralised ECR registry.
+    environment: dev
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
+
+      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
         if: ${{ env.RUN_UNIT_TESTS == 'true' }}
         with:
           python-version: "3.11"
-          cache: pip
-          cache-dependency-path: health_pubs/requirements.txt
+          cache: "pip"
 
-      - name: Install dependencies
+      - name: Unit tests
         if: ${{ env.RUN_UNIT_TESTS == 'true' }}
-        run: pip install -r requirements.txt
-        working-directory: health_pubs
-
-      - name: Run tests
-        if: ${{ env.RUN_UNIT_TESTS == 'true' }}
-        run: pytest
-        working-directory: health_pubs
-
-  build_and_push:
-    name: Build & push image to ECR
-    runs-on: ubuntu-latest
-    needs: test
-    steps:
-      - uses: actions/checkout@v4
+        run: |
+          cd health_pubs
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pytest
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708
+        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
         with:
           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
           role-session-name: build-${{ github.sha }}
           aws-region: ${{ env.AWS_REGION }}
+      
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
 
-      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
 
-      - id: login-ecr
-        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076
-
-      - name: Build & push
-        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
+      - name: Build container image
+        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
         env:
-          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          IMAGE: ${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         with:
           context: .
-          push: true
-          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
-          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
+          push: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production') && github.event_name == 'push' }}
+          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ github.sha }},${{ env.ECR_REGISTRY }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:latest
+          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:latest
           cache-to: type=inline
+
+  release:
+    name: Tag and release container image
+    runs-on: ubuntu-latest
+    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production') && github.event_name == 'push'
+    environment: dev
+    permissions:
+      contents: write
+      id-token: write
+      actions: read
+    needs:
+      - build
+    outputs:
+      release_tag: ${{ steps.tag_bump.outputs.new_tag }}
+    steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
+
+      - uses: ukhsa-collaboration/devops-github-actions/.github/actions/github-bump-tag@ea0aa2a80fccfb2a19e1c71443a0a60b85f618a8 # v0.11.0
+        id: tag_bump
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          WITH_V: true
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
+        with:
+          # AWS_ACCOUNT_ID_ECR_REGISTRY is used for pulling from a shared ECR repository
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
+          role-session-name: retag-image-${{ github.sha }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
+
+      - name: Pull, retag, and push Application image for release
+        id: push
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          IMAGE_TAG: ${{ github.sha }}
+        run: |
+          docker pull $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:$IMAGE_TAG
+          docker tag $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:${{ steps.tag_bump.outputs.new_tag }}
+          docker push $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:${{ steps.tag_bump.outputs.new_tag }}
+  
+  release-hotfix:
+    name: Hotfix Tag and release container image 
+    runs-on: ubuntu-latest
+    if: (github.ref == 'refs/heads/production') && contains(github.event.head_commit.message, 'hotfix/HPUB')
+    environment: dev
+    permissions:
+      contents: write
+      id-token: write
+      actions: read
+    needs:
+      - build
+    steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
+        with:
+          fetch-depth: 0 
+      
+      - name: Get latest GitHub release
+        id: latest_release
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REPO: ${{ github.repository }}
+        run: |
+          LATEST_RELEASE_TAG=$(curl -s -H "Authorization: token $GH_TOKEN" \
+            https://api.github.com/repos/$REPO/releases/latest \
+            | jq -r '.tag_name')
+
+          VERSION_NUMBER=${LATEST_RELEASE_TAG#v}
+          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUMBER"
+          
+          # Fetch all tags locally
+          git fetch --tags > /dev/null 2>&1
+
+          # Find the highest patch for this MAJOR.MINOR
+          LATEST_PATCH=$(git tag -l "v${MAJOR}.${MINOR}.*" \
+            | sed "s/v${MAJOR}.${MINOR}.//" \
+            | sort -n \
+            | tail -1)
+
+          # If no tags found, start at 0
+          LATEST_PATCH=${LATEST_PATCH:-0}
+
+          # Increment PATCH from the latest one
+          PATCH=$((LATEST_PATCH + 1))
+
+          # Build new tag
+          NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
+          echo "HOTFIX_TAG=$NEW_TAG" >> $GITHUB_ENV
+          echo "Latest release: $LATEST_RELEASE_TAG"
+          echo "New hotfix tag: $HOTFIX_TAG"
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
+        with:
+          # AWS_ACCOUNT_ID_ECR_REGISTRY is used for pulling from a shared ECR repository
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
+          role-session-name: retag-image-${{ github.sha }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
+      
+      - name: Setup Git
+        run: |
+          git config user.name "${GITHUB_ACTOR}"
+          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+
+      # Create Git tag
+      - name: Create tag
+        run: |
+          git tag -a $HOTFIX_TAG -m "Hotfix: $HOTFIX_TAG"
+      
+      # Push tag to remote
+      - name: Push tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git push origin $HOTFIX_TAG
+
+      - name: Pull, retag, and push Application image for release
+        id: push
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          IMAGE_TAG: ${{ github.sha }}
+        run: |
+          docker pull $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:$IMAGE_TAG
+          docker tag $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:$HOTFIX_TAG
+          docker push $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:$HOTFIX_TAG
+
+  deploy_to_nonprod:
+    name: Deploy build to ${{ matrix.environment }}
+    runs-on: ubuntu-latest
+    environment: ${{ matrix.environment }}
+    strategy:
+      max-parallel: 1
+      matrix:
+        environment: ["dev", "test"]
+    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+    permissions:
+      contents: write
+      id-token: write
+      actions: read
+    needs:
+      - release
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
+          role-session-name: deploy-${{ github.sha }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Update Parameter Store with new value
+        env:
+          NEW_TAG: ${{ needs.release.outputs.release_tag }}
+        run: |
+          aws ssm put-parameter --name "/hpub/$APP_NAME/image_tag" --type "String" --value "$NEW_TAG" --overwrite
+
+      - name: Download task definition
+        run: |
+          aws ecs describe-task-definition --task-definition aw-hpub-euw2-${{ matrix.environment }}-ecssvc-$APP_NAME --query taskDefinition > task-definition.json
+
+      - name: Modify Amazon ECS task definition with updated image URI
+        id: render-task-def
+        uses: aws-actions/amazon-ecs-render-task-definition@06472d439cb66af6210a6709bfc842c26b053706 # v1
+        with:
+          task-definition: task-definition.json
+          container-name: app
+          # We have to construct this as Github Actions will refuse to pass the full URL from 'release' step as it contains an AWS account ID
+          image: ${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ needs.release.outputs.release_tag }}
+
+      - name: Deploy to Amazon ECS
+        uses: aws-actions/amazon-ecs-deploy-task-definition@c6e19c08506099e50400581201a3a767fd8e3ff4 # v2
+        with:
+          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
+          service: aw-hpub-euw2-${{ matrix.environment }}-ecssvc-${{ env.APP_NAME }}
+          cluster: aw-hpub-euw2-${{ matrix.environment }}-ecscluster
+          wait-for-service-stability: true
+
+      - name: Determine Base URL
+        id: url
+        env:
+          environment: ${{ matrix.environment }}
+        run: |
+          if [ "$environment" == "prd" ]; then
+            prefix=hpub
+          elif [ "$environment" == "preprod" ]; then
+            prefix=hpubpp
+          elif [ "$environment" == "prod" ]; then
+            prefix=hpub
+          elif [ "$environment" == "uat" ]; then
+            prefix=hpub-uat
+          elif [ "$environment" == "test" ]; then
+            prefix=hpub-test
+          elif [ "$environment" == "dev" ]; then
+            prefix=hpub-dev
+          else
+            echo "Unknown environment. Unable to run tests."
+            exit 1
+          fi
+          echo prefix=$prefix >> $GITHUB_OUTPUT
+
+      - name: End-to-end tests
+        if: ${{ matrix.environment != 'prod' && matrix.environment != 'preprod' }}
+        env:
+          BASE_URL: "https://${{ steps.url.outputs.prefix }}.test-and-trace.nhs.uk"
+        run: |
+          # No end-to-end testing in place yet
+          echo npx playwright test
+
+      - name: Post-Deployment Smoke Test
+        if: ${{ matrix.environment != 'prod' && matrix.environment != 'preprod' }}
+        env:
+          environment_prefix: ${{ steps.url.outputs.prefix }}
+        shell: bash
+        run: |
+          response=$(curl -H "user-agent: Mozilla/5.0 (compatible; PostDeploymentHealthCheck)" -s -o /dev/null -w "%{http_code}" https://$environment_prefix.test-and-trace.nhs.uk/api/v1/health/)
+          if [ "$response" -ne 200 ]; then
+            echo "Post-Deployment tests failed!"
+            exit 1
+          fi
